spring:
  datasource:
    url:
      jdbc:h2:mem:db
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'